apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-{{ .Values.deployEnv }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.appName }}-{{ .Values.deployEnv }}
    release: prometheus-stack
spec:
  replicas: {{ .Values.defaultReplicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.appName }}-{{ .Values.deployEnv}}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}-{{ .Values.deployEnv}}
        release: prometheus-stack
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Values.appName }}-{{ .Values.deployEnv }}
          matchLabelKeys:
            - pod-template-hash
      containers:
        - name: {{ .Values.appName }}-{{ .Values.deployEnv}}
          image: "{{  .Values.imageRepo }}:{{ .Values.imageTag }}"
          env:
            - name: APP_ENV
              value: {{ .Values.deployEnv }}
            - name: APP_VERSION
              value: {{ .Values.appVersion | quote }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          resources:
            limits:
              cpu: {{ .Values.cpuLimit }}
              memory: {{ .Values.memoryLimit }}
            requests:
              cpu: {{ .Values.cpuRequest }}
              memory: {{ .Values.memoryRequest }}
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com
