#!/usr/bin/env sh

STAGED=$(git diff --cached --name-only)

echo "Running cspell on staged files..."
echo "$STAGED" | xargs ./node_modules/.bin/cspell --show-suggestions

if [ $? -ne 0 ]; then
    echo "❌ Commit failed: Spelling errors detected by cspell."
    exit 1
fi

echo "✅ No spelling errors found."
exit 0
