name: Build prod image

on:
  push:
    branches: [ main ]

# jobs with same concurrency label will be put in pending state
concurrency: prod-ci

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          # docusaurus checks .git for history, so we need all commits
          fetch-depth: 0
          submodules: recursive

      # For gha cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_URL }}

      - uses: docker/build-push-action@v3
        with:
          # To pass .git for docusaurus
          context: .
          file: "deployment/Docker/Dockerfile"
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.REGISTRY_URL }}/nwt/ton_docs:${{ github.sha }}
          push: true

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: "deployment/Docker/Dockerfile"
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ secrets.REGISTRY_URL }}/nwt/ton_docs:latest
          push: true

      - name: Trigger deploy
        run: curl -s "${{ secrets.CD_URL }}"
